### ISSUE TITLE
ログインボタンを押すとエラーが出る

### ISSUE THREAD

**Issue by fumiya-kume** [r-ralph/C91XamarinFacebookSample#1]
# 環境
Xamarin.iOS
6S iOS 10.2 エミュレータ

![devenv_2017-01-01_02-52-58](https://cloud.githubusercontent.com/assets/16269075/21578700/cfc53820-cfcd-11e6-9aa7-5b4f54c03678.png)

![image](https://cloud.githubusercontent.com/assets/16269075/21578696/c0086056-cfcd-11e6-8e41-ea7af471e985.png)

**Comment by r-ralph** [comment]
申し訳ない、iOSの方は未対応なんです・・・（コミケの記事でもAndroidだけしか書いていないです・・・）

**Comment by fumiya-kume** [comment]
失礼しました。
issueは閉じた方がいいですか？

**Comment by r-ralph** [comment]
いえいえー
iOSの方もいつか対応したいですね。。
（issueはこちらで閉じておきます）
